name: DEPLOY TO STAGING

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_PW: ${{ secrets.AWS_DB_PW }}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Create .env File
        run: |
          touch .env
          echo DB_HOST="$DB_HOST" >> .env
          echo DB_PW="$DB_PW" >> .env
          echo DB_USER="$DB_USER" >> .env
          echo DB_NAME="$DB_NAME" >> .env

      - name: Run Database Migrations
        run: npm run migrate  # Ensure schema is up to date

      - name: Seed Database if Needed
        run: |
          if [ "$(node scripts/checkSeed.js)" = "empty" ]; then
            npm run seed:all
          else
            echo "Seeding skipped: Data already exists."
          fi

      - name: Bundle Application
        run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "flightplan.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/2025/flight-plan/t6"

      - name: Execute SSH Commands on Remote Server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@flightplan.eaglesoftwareteam.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/2025/flight-plan/t6
            npm install
            sudo systemctl stop flight-plan-t6-backend
            sudo cp flight-plan-t6-backend.service /lib/systemd/system/flight-plan-t6-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start flight-plan-t6-backend
